#!/usr/bin/env python3
"""
nightwind.ai i18n build script.
Source of truth: template.html
Run: python3 build.py
Generates: index.html + de/ fr/ es/ ar/ he/ pt/ subdirectories
"""

import os

ACTIVE   = "text-signal-green"
INACTIVE = "text-text-muted"

LANGS = {

  'en': {
    'LANG_CODE': 'en',
    'DIR': 'ltr',
    'CONF_BORDER': 'border-l-2 border-l-signal-green',
    'OG_LOCALE': 'en_GB',
    'CANONICAL': 'https://nightwind.ai/',
    'ASSET_PATH': '',
    'ROOT_PATH': '/',
    'PAGE_TITLE': 'nightwind.ai | Airgapped AI Document Intelligence',
    'META_DESC': 'Airgapped AI document intelligence for defence, intelligence, and national security organisations. On-premise deployment. No cloud dependency. Fully sovereign. Perpetual licence.',
    'META_OG_DESC': 'Query decades of unstructured intelligence archives using natural language. Deployed on-premise. No cloud dependency. Fully sovereign.',
    'CLASSIFICATION_BANNER': '// AIRGAPPED INTELLIGENCE //',
    'HERO_H1': 'Airgapped AI<br>document intelligence.',
    'HERO_SUBTEXT': 'Query decades of unstructured intelligence archives using natural language. Deployed on-premise. No cloud dependency. Fully sovereign.',
    'HERO_TAGLINE': 'Built for defence, intelligence, and national security organisations.',
    'HERO_CTA': 'REQUEST A BRIEFING',
    'LOCAL_NAME': '',
    'PROBLEM_LABEL': 'The Problem',
    'PROBLEM_H2': 'Your analysts spend more time searching than analysing.',
    'PROBLEM_C1_LABEL': '[LEGACY DATA]',
    'PROBLEM_C1_TEXT': 'Terabytes of intelligence reports, field assessments, and policy documents accumulated over decades — locked in formats that resist modern search.',
    'PROBLEM_C2_LABEL': '[INEFFICIENCY]',
    'PROBLEM_C2_TEXT': '60–70% of analyst time consumed by manual document retrieval. Knowledge that should take seconds to surface takes hours or days.',
    'PROBLEM_C3_LABEL': '[VENDOR DEPENDENCY]',
    'PROBLEM_C3_TEXT': 'Existing solutions require cloud connectivity and create foreign vendor lock-in — incompatible with sovereign operations and national security requirements.',
    'PLATFORM_LABEL': 'The Platform',
    'PLATFORM_H2': 'Ask questions. Get cited answers. Stay airgapped.',
    'CAP1_TITLE': '[01] ASK IN ANY LANGUAGE',
    'CAP1_TEXT': 'Your analysts ask questions the way they think — in English, Arabic, French, or any language they work in. The platform searches your entire document archive and returns cited, sourced answers in seconds.',
    'CAP2_TITLE': '[02] AIRGAPPED BY DESIGN',
    'CAP2_TEXT': 'Deployed entirely on-premise, behind your air gap. No cloud connectivity. No data leaves your infrastructure. Complete security control from day one.',
    'CAP3_TITLE': '[03] MODEL FLEXIBLE',
    'CAP3_TEXT': 'Works with open-source and proprietary AI models. Choose the models that meet your security and performance requirements. No single-vendor dependency.',
    'CAP4_TITLE': '[04] READS YOUR DOCUMENTS',
    'CAP4_TEXT': 'PDFs, Word documents, and text-based files — your existing document archives are searchable from day one, in any language, without reformatting or migration.',
    'POS_LABEL': 'Positioning',
    'POS_H2': 'Sovereign AI. Airgapped by design.',
    'POS_SUBTEXT': 'Purpose-built for organisations that cannot send data to the cloud and require full operational independence.',
    'POS1_TITLE': 'ZERO CLOUD',
    'POS1_TEXT': 'Not "cloud-optional." Not "hybrid." Airgapped from day one. Your data never leaves your infrastructure. Ever.',
    'POS2_TITLE': 'NO LOCK-IN',
    'POS2_TEXT': 'No subscriptions, no per-seat fees, no renewal negotiations. Open standards. Perpetual licence. Your data, your models, your sovereignty.',
    'POS3_TITLE': 'FULL AUDIT TRAIL',
    'POS3_TEXT': 'Every query logged. Every answer traceable to source documents. Complete accountability built into the platform from the ground up.',
    'UC_LABEL': 'Operational Context',
    'UC_H2': 'Built for your operating environment.',
    'UC1_TITLE': 'DEFENCE INTELLIGENCE ANALYSIS',
    'UC1_QUOTE': 'What did allied assessments conclude about [threat actor] supply chain dependencies between 2015–2024?',
    'UC1_TEXT': 'Surface cross-referenced intelligence from decades of archived reports in seconds. Full citation chain. Analyst-verifiable sources.',
    'UC2_TITLE': 'DEFENCE PROCUREMENT',
    'UC2_QUOTE': 'Which evaluation reports reference performance issues with [equipment type] in theatre conditions?',
    'UC2_TEXT': 'Query decades of technical evaluations, field reports, and after-action reviews without manual document retrieval.',
    'UC3_TITLE': 'NATIONAL SECURITY POLICY',
    'UC3_QUOTE': 'How have threat assessments for [region] evolved across the last three strategic defence reviews?',
    'UC3_TEXT': 'Synthesise temporal patterns across policy documents, intelligence summaries, and ministerial briefings.',
    'CONF_LABEL': 'Confidentiality',
    'CONF_H2': 'Full confidentiality. No exceptions.',
    'CONF_TEXT': 'Every engagement — from initial briefing to deployment — is conducted under strict NDA. Client identities, deployment configurations, and operational details are never disclosed in any context, to any party, for any purpose. What you deploy stays classified.',
    'FAQ_LABEL': 'FAQ',
    'FAQ_H2': 'Common questions.',
    'FAQ_Q1': 'Does nightwind.ai require cloud connectivity?',
    'FAQ_A1': 'No. nightwind.ai is fully airgapped. All processing occurs on customer-owned infrastructure inside the customer\'s own security perimeter. No data ever leaves the facility.',
    'FAQ_Q2': 'What languages does nightwind.ai support?',
    'FAQ_A2': 'Any language. There is no language limitation. Operators can query in English, Arabic, French, Mandarin, Russian, Spanish, or any other language. Mixed-language archives are supported.',
    'FAQ_Q3': 'What is the licensing model?',
    'FAQ_A3': 'Perpetual licence. No subscription fees, no per-seat charges, no recurring vendor dependency. After deployment, customers own all components.',
    'FAQ_Q4': 'Is nightwind.ai suitable for classified networks?',
    'FAQ_A4': 'Yes. nightwind.ai is designed for classified and sensitive environments. Zero network dependencies, no telemetry, no vendor call-home. Compatible with air-gapped and classified network environments.',
    'FAQ_Q5': 'What document formats are supported?',
    'FAQ_A5': 'PDFs, Word documents, and text-based files. Existing archives in these formats are fully searchable from day one, without reformatting or migration.',
    'FAQ_Q6': 'Does nightwind.ai require ongoing subscriptions?',
    'FAQ_A6': 'No. Perpetual licence. No recurring fees, no per-seat charges, no renewal negotiations. Customers own all deployed components outright.',
    'CONTACT_LABEL': 'Contact',
    'CONTACT_H2': 'Request a briefing.',
    'CONTACT_SUBTEXT': 'Technical briefings and deployment documentation are available to verified organisations under NDA.',
    'FOOTER_TAGLINE': 'Airgapped AI document intelligence. Sovereign technology.',
    'FOOTER_NAV_CAP': 'Capabilities',
    'FOOTER_NAV_UC': 'Use Cases',
    'FOOTER_NAV_FAQ': 'FAQ',
    'FOOTER_NAV_CONTACT': 'Contact',
    'FOOTER_COPYRIGHT': '&copy; 2026 nightwind.ai. All rights reserved.',
  },

  'ar': {
    'LANG_CODE': 'ar',
    'DIR': 'rtl',
    'CONF_BORDER': 'border-r-2 border-r-signal-green',
    'OG_LOCALE': 'ar_SA',
    'CANONICAL': 'https://nightwind.ai/ar/',
    'ASSET_PATH': '../',
    'ROOT_PATH': 'https://nightwind.ai/',
    'PAGE_TITLE': 'nightwind.ai | ذكاء الوثائق بالذكاء الاصطناعي المعزول',
    'META_DESC': 'ذكاء الوثائق بالذكاء الاصطناعي المعزول للدفاع والاستخبارات ومنظمات الأمن القومي. نشر محلي. لا اعتماد على السحابة. سيادة كاملة. ترخيص دائم.',
    'META_OG_DESC': 'استعلم عن عقود من أرشيفات الاستخبارات غير المنظمة باللغة الطبيعية. نشر محلي. لا اعتماد على السحابة. سيادة كاملة.',
    'CLASSIFICATION_BANNER': '// ذكاء معزول //',
    'HERO_H1': 'ذكاء الوثائق بالذكاء<br>الاصطناعي المعزول.',
    'HERO_SUBTEXT': 'استعلم عن عقود من أرشيفات الاستخبارات غير المنظمة باللغة الطبيعية. نشر محلي. لا اعتماد على السحابة. سيادة كاملة.',
    'HERO_TAGLINE': 'مُصمَّم للدفاع والاستخبارات ومنظمات الأمن القومي.',
    'HERO_CTA': 'طلب إحاطة',
    'LOCAL_NAME': '<p class="font-mono font-bold text-xl text-text-primary mt-1" dir="rtl">ريح الليل <span class="text-signal-green">AI</span></p>',
    'PROBLEM_LABEL': 'المشكلة',
    'PROBLEM_H2': 'يقضي محلّلوكم وقتاً أطول في البحث من التحليل.',
    'PROBLEM_C1_LABEL': '[البيانات القديمة]',
    'PROBLEM_C1_TEXT': 'تيرابايتات من تقارير الاستخبارات وتقييمات الميدان والوثائق السياسية المتراكمة على مدى عقود — محجوزة في تنسيقات تعيق البحث الحديث.',
    'PROBLEM_C2_LABEL': '[عدم الكفاءة]',
    'PROBLEM_C2_TEXT': 'يُستهلك 60–70% من وقت المحلّل في استرجاع الوثائق يدوياً. معرفة يُفترض أن تظهر في ثوانٍ تستغرق ساعات أو أياماً.',
    'PROBLEM_C3_LABEL': '[التبعية للمورّد]',
    'PROBLEM_C3_TEXT': 'تتطلب الحلول الحالية الاتصال بالسحابة وتُنشئ تبعية لمورّدين أجانب — وهو أمر يتعارض مع العمليات السيادية ومتطلبات الأمن القومي.',
    'PLATFORM_LABEL': 'المنصة',
    'PLATFORM_H2': 'اطرح أسئلة. احصل على إجابات موثّقة. ابقَ معزولاً.',
    'CAP1_TITLE': '[01] الاستعلام بأي لغة',
    'CAP1_TEXT': 'يطرح محلّلوك أسئلة بالطريقة التي يفكّرون بها — بالعربية أو الإنجليزية أو الفرنسية أو أي لغة يعملون بها. تبحث المنصة في أرشيف وثائقك بالكامل وتُعيد إجابات موثّقة بالمصادر في ثوانٍ.',
    'CAP2_TITLE': '[02] معزول بالتصميم',
    'CAP2_TEXT': 'نشر كامل محلياً خلف حاجز الهواء. لا اتصال بالسحابة. لا تغادر البيانات بنيتك التحتية. سيطرة أمنية كاملة منذ اليوم الأول.',
    'CAP3_TITLE': '[03] مرونة النموذج',
    'CAP3_TEXT': 'يعمل مع نماذج الذكاء الاصطناعي مفتوحة المصدر والملكية. اختر النماذج التي تلبّي متطلبات الأمان والأداء لديك. لا تبعية لمورّد واحد.',
    'CAP4_TITLE': '[04] يقرأ وثائقك',
    'CAP4_TEXT': 'ملفات PDF ووثائق Word والملفات النصية — أرشيفات وثائقك الحالية قابلة للبحث منذ اليوم الأول، بأي لغة، دون إعادة تنسيق أو ترحيل.',
    'POS_LABEL': 'التموضع',
    'POS_H2': 'ذكاء اصطناعي سيادي. معزول بالتصميم.',
    'POS_SUBTEXT': 'مُصمَّم خصيصاً للمنظمات التي لا تستطيع إرسال البيانات إلى السحابة وتتطلب استقلالية تشغيلية كاملة.',
    'POS1_TITLE': 'لا سحابة',
    'POS1_TEXT': 'ليس "اختيارياً للسحابة". ليس "هجيناً". معزول منذ اليوم الأول. بياناتك لا تغادر بنيتك التحتية أبداً. أبداً.',
    'POS2_TITLE': 'لا تبعية',
    'POS2_TEXT': 'لا اشتراكات، لا رسوم لكل مقعد، لا مفاوضات تجديد. معايير مفتوحة. ترخيص دائم. بياناتك، نماذجك، سيادتك.',
    'POS3_TITLE': 'سجل تدقيق كامل',
    'POS3_TEXT': 'كل استعلام مُسجَّل. كل إجابة قابلة للتتبع حتى الوثائق المصدر. مساءلة كاملة مبنية في المنصة من الأساس.',
    'UC_LABEL': 'السياق التشغيلي',
    'UC_H2': 'مُصمَّم لبيئتك التشغيلية.',
    'UC1_TITLE': 'تحليل الاستخبارات الدفاعية',
    'UC1_QUOTE': 'ما الذي خلصت إليه التقييمات الحليفة بشأن تبعيات سلسلة التوريد لـ[جهة التهديد] بين 2015–2024؟',
    'UC1_TEXT': 'استخرج استخبارات متقاطعة المراجع من عقود من التقارير المؤرشفة في ثوانٍ. سلسلة اقتباس كاملة. مصادر قابلة للتحقق من المحلّل.',
    'UC2_TITLE': 'المشتريات الدفاعية',
    'UC2_QUOTE': 'ما تقارير التقييم التي تُشير إلى مشكلات أداء في [نوع المعدات] في ظروف الميدان؟',
    'UC2_TEXT': 'استعلم عن عقود من التقييمات التقنية وتقارير الميدان ومراجعات ما بعد العمليات دون استرجاع يدوي للوثائق.',
    'UC3_TITLE': 'سياسة الأمن القومي',
    'UC3_QUOTE': 'كيف تطوّرت تقييمات التهديد لـ[المنطقة] عبر مراجعات الدفاع الاستراتيجية الثلاث الأخيرة؟',
    'UC3_TEXT': 'اصنع أنماطاً زمنية عبر وثائق السياسات وملخصات الاستخبارات والإحاطات الوزارية.',
    'CONF_LABEL': 'السرية',
    'CONF_H2': 'سرية تامة. بلا استثناءات.',
    'CONF_TEXT': 'كل تعامل — من الإحاطة الأولية حتى النشر — يُجرى بموجب اتفاقية سرية صارمة. هويات العملاء وتكوينات النشر والتفاصيل التشغيلية لا تُكشف في أي سياق، لأي طرف، لأي غرض. ما تنشره يبقى سرياً.',
    'FAQ_LABEL': 'الأسئلة الشائعة',
    'FAQ_H2': 'أسئلة متكررة.',
    'FAQ_Q1': 'هل تتطلب nightwind.ai اتصالاً بالسحابة؟',
    'FAQ_A1': 'لا. nightwind.ai معزولة تماماً. تتم جميع المعالجات على البنية التحتية المملوكة للعميل داخل محيط أمانه الخاص. لا تغادر البيانات المنشأة أبداً.',
    'FAQ_Q2': 'ما اللغات التي تدعمها nightwind.ai؟',
    'FAQ_A2': 'أي لغة. لا يوجد قيد على اللغة. يمكن للمشغّلين الاستعلام بالعربية أو الإنجليزية أو الفرنسية أو الماندرين أو الروسية أو الإسبانية أو أي لغة أخرى. تُدعم الأرشيفات متعددة اللغات.',
    'FAQ_Q3': 'ما نموذج الترخيص؟',
    'FAQ_A3': 'ترخيص دائم. لا رسوم اشتراك، لا رسوم لكل مقعد، لا تبعية متكررة للمورّد. بعد النشر، يمتلك العملاء جميع المكونات.',
    'FAQ_Q4': 'هل nightwind.ai مناسبة للشبكات المصنّفة؟',
    'FAQ_A4': 'نعم. nightwind.ai مصمّمة للبيئات المصنّفة والحساسة. صفر تبعيات شبكة، لا قياس عن بُعد، لا اتصال عكسي بالمورّد. متوافقة مع بيئات الشبكة المعزولة والمصنّفة.',
    'FAQ_Q5': 'ما تنسيقات المستندات المدعومة؟',
    'FAQ_A5': 'ملفات PDF ووثائق Word والملفات النصية. الأرشيفات الحالية بهذه التنسيقات قابلة للبحث الكامل منذ اليوم الأول، دون إعادة تنسيق أو ترحيل.',
    'FAQ_Q6': 'هل تتطلب nightwind.ai اشتراكات مستمرة؟',
    'FAQ_A6': 'لا. ترخيص دائم. لا رسوم متكررة، لا رسوم لكل مقعد، لا مفاوضات تجديد. يمتلك العملاء جميع المكونات المنشورة بالكامل.',
    'CONTACT_LABEL': 'التواصل',
    'CONTACT_H2': 'طلب إحاطة.',
    'CONTACT_SUBTEXT': 'الإحاطات التقنية ووثائق النشر متاحة للمنظمات الموثّقة بموجب اتفاقية سرية.',
    'FOOTER_TAGLINE': 'ذكاء الوثائق بالذكاء الاصطناعي المعزول. تقنية سيادية.',
    'FOOTER_NAV_CAP': 'القدرات',
    'FOOTER_NAV_UC': 'حالات الاستخدام',
    'FOOTER_NAV_FAQ': 'الأسئلة الشائعة',
    'FOOTER_NAV_CONTACT': 'التواصل',
    'FOOTER_COPYRIGHT': '&copy; 2026 nightwind.ai. جميع الحقوق محفوظة.',
  },

  'de': {
    'LANG_CODE': 'de',
    'DIR': 'ltr',
    'CONF_BORDER': 'border-l-2 border-l-signal-green',
    'OG_LOCALE': 'de_DE',
    'CANONICAL': 'https://nightwind.ai/de/',
    'ASSET_PATH': '../',
    'ROOT_PATH': 'https://nightwind.ai/',
    'PAGE_TITLE': 'nightwind.ai | Airgapped KI-Dokumentenanalyse',
    'META_DESC': 'Airgapped KI-Dokumentenanalyse für Verteidigung, Nachrichtendienste und nationale Sicherheitsbehörden. On-Premise-Betrieb. Keine Cloud-Abhängigkeit. Vollständig souverän. Dauerlizenz.',
    'META_OG_DESC': 'Jahrzehnte unstrukturierter Nachrichtenarchive per natürlicher Sprache abfragen. On-Premise betrieben. Keine Cloud-Abhängigkeit. Vollständig souverän.',
    'CLASSIFICATION_BANNER': '// AIRGAPPED INTELLIGENCE //',
    'HERO_H1': 'Airgapped KI-<br>Dokumentenanalyse.',
    'HERO_SUBTEXT': 'Jahrzehnte unstrukturierter Nachrichtenarchive per natürlicher Sprache abfragen. On-Premise betrieben. Keine Cloud-Abhängigkeit. Vollständig souverän.',
    'HERO_TAGLINE': 'Entwickelt für Verteidigung, Nachrichtendienste und nationale Sicherheitsbehörden.',
    'HERO_CTA': 'BRIEFING ANFORDERN',
    'LOCAL_NAME': '',
    'PROBLEM_LABEL': 'Das Problem',
    'PROBLEM_H2': 'Ihre Analysten verbringen mehr Zeit mit Suchen als mit Analysieren.',
    'PROBLEM_C1_LABEL': '[ALTDATEN]',
    'PROBLEM_C1_TEXT': 'Terabytes von Geheimdienstberichten, Lagebeurteilungen und Grundsatzdokumenten, über Jahrzehnte angehäuft — in Formaten gesperrt, die moderner Suche widerstehen.',
    'PROBLEM_C2_LABEL': '[INEFFIZIENZ]',
    'PROBLEM_C2_TEXT': '60–70 % der Analystezeit wird durch manuelle Dokumentenrecherche verbraucht. Wissen, das Sekunden brauchen sollte, benötigt Stunden oder Tage.',
    'PROBLEM_C3_LABEL': '[LIEFERANTENABHÄNGIGKEIT]',
    'PROBLEM_C3_TEXT': 'Bestehende Lösungen erfordern Cloud-Konnektivität und schaffen ausländische Lieferantenabhängigkeit — unvereinbar mit souveränem Betrieb und nationalen Sicherheitsanforderungen.',
    'PLATFORM_LABEL': 'Die Plattform',
    'PLATFORM_H2': 'Fragen stellen. Zitierte Antworten erhalten. Airgapped bleiben.',
    'CAP1_TITLE': '[01] IN JEDER SPRACHE ABFRAGEN',
    'CAP1_TEXT': 'Ihre Analysten stellen Fragen so, wie sie denken — auf Deutsch, Arabisch, Französisch oder jeder anderen Arbeitssprache. Die Plattform durchsucht das gesamte Dokumentarchiv und liefert in Sekunden zitierte, quellenbasierte Antworten.',
    'CAP2_TITLE': '[02] AIRGAPPED BY DESIGN',
    'CAP2_TEXT': 'Vollständig On-Premise hinter Ihrer Air-Gap betrieben. Keine Cloud-Konnektivität. Keine Daten verlassen Ihre Infrastruktur. Vollständige Sicherheitskontrolle vom ersten Tag an.',
    'CAP3_TITLE': '[03] MODELLFLEXIBEL',
    'CAP3_TEXT': 'Funktioniert mit Open-Source- und proprietären KI-Modellen. Wählen Sie Modelle, die Ihren Sicherheits- und Leistungsanforderungen entsprechen. Keine Abhängigkeit von einem einzelnen Lieferanten.',
    'CAP4_TITLE': '[04] LIEST IHRE DOKUMENTE',
    'CAP4_TEXT': 'PDFs, Word-Dokumente und textbasierte Dateien — Ihre bestehenden Dokumentarchive sind vom ersten Tag an in jeder Sprache durchsuchbar, ohne Neuformatierung oder Migration.',
    'POS_LABEL': 'Positionierung',
    'POS_H2': 'Souveräne KI. Airgapped by Design.',
    'POS_SUBTEXT': 'Entwickelt für Organisationen, die keine Daten in die Cloud senden können und vollständige operative Unabhängigkeit benötigen.',
    'POS1_TITLE': 'NULL CLOUD',
    'POS1_TEXT': 'Nicht „cloud-optional". Nicht „hybrid". Airgapped vom ersten Tag an. Ihre Daten verlassen Ihre Infrastruktur niemals. Niemals.',
    'POS2_TITLE': 'KEINE ANBIETERBINDUNG',
    'POS2_TEXT': 'Keine Abonnements, keine Lizenzgebühren pro Arbeitsplatz, keine Verlängerungsverhandlungen. Offene Standards. Dauerlizenz. Ihre Daten, Ihre Modelle, Ihre Souveränität.',
    'POS3_TITLE': 'VOLLSTÄNDIGES PRÜFPROTOKOLL',
    'POS3_TEXT': 'Jede Anfrage protokolliert. Jede Antwort auf Quelldokumente zurückverfolgbar. Vollständige Rechenschaftspflicht von Grund auf in die Plattform eingebaut.',
    'UC_LABEL': 'Einsatzkontext',
    'UC_H2': 'Entwickelt für Ihre Einsatzumgebung.',
    'UC1_TITLE': 'GEHEIMDIENSTLICHE LAGEANALYSE',
    'UC1_QUOTE': 'Welche Schlussfolgerungen zogen alliierte Bewertungen zu den Lieferkettenabhängigkeiten von [Bedrohungsakteur] zwischen 2015–2024?',
    'UC1_TEXT': 'Querverweise auf Erkenntnisse aus Jahrzehnten archivierter Berichte in Sekunden. Vollständige Zitierungskette. Analysten-verifizierbare Quellen.',
    'UC2_TITLE': 'VERTEIDIGUNGSBESCHAFFUNG',
    'UC2_QUOTE': 'Welche Bewertungsberichte verweisen auf Leistungsprobleme bei [Ausrüstungstyp] unter Feldbedingungen?',
    'UC2_TEXT': 'Jahrzehnte technischer Bewertungen, Feldberichte und Nachbetrachtungsberichte ohne manuelle Dokumentenrecherche abfragen.',
    'UC3_TITLE': 'NATIONALE SICHERHEITSPOLITIK',
    'UC3_QUOTE': 'Wie haben sich die Bedrohungsbewertungen für [Region] über die letzten drei strategischen Verteidigungsüberprüfungen entwickelt?',
    'UC3_TEXT': 'Zeitliche Muster über Grundsatzdokumente, Geheimdienstzusammenfassungen und Ministerialberichte hinweg synthetisieren.',
    'CONF_LABEL': 'Vertraulichkeit',
    'CONF_H2': 'Vollständige Vertraulichkeit. Keine Ausnahmen.',
    'CONF_TEXT': 'Jedes Engagement — vom ersten Briefing bis zum Deployment — wird unter strikter NDA durchgeführt. Kundenidentitäten, Deployment-Konfigurationen und operative Details werden in keinem Kontext, gegenüber keiner Partei und für keinen Zweck offengelegt. Was Sie einsetzen, bleibt klassifiziert.',
    'FAQ_LABEL': 'FAQ',
    'FAQ_H2': 'Häufige Fragen.',
    'FAQ_Q1': 'Benötigt nightwind.ai Cloud-Konnektivität?',
    'FAQ_A1': 'Nein. nightwind.ai ist vollständig airgapped. Alle Verarbeitungen finden auf kundeneigener Infrastruktur innerhalb des Sicherheitsperimeters des Kunden statt. Keine Daten verlassen das System.',
    'FAQ_Q2': 'Welche Sprachen unterstützt nightwind.ai?',
    'FAQ_A2': 'Jede Sprache. Es gibt keine Sprachbeschränkung. Operatoren können auf Englisch, Arabisch, Französisch, Mandarin, Russisch, Spanisch oder jeder anderen Sprache abfragen. Mehrsprachige Archive werden unterstützt.',
    'FAQ_Q3': 'Wie lautet das Lizenzmodell?',
    'FAQ_A3': 'Dauerlizenz. Keine Abonnementgebühren, keine Gebühren pro Arbeitsplatz, keine wiederkehrende Lieferantenabhängigkeit. Nach dem Deployment besitzen Kunden alle Komponenten.',
    'FAQ_Q4': 'Ist nightwind.ai für klassifizierte Netzwerke geeignet?',
    'FAQ_A4': 'Ja. nightwind.ai ist für klassifizierte und sensible Umgebungen entwickelt. Null Netzwerkabhängigkeiten, keine Telemetrie, kein Lieferanten-Rückruf. Kompatibel mit Airgapped- und klassifizierten Netzwerkumgebungen.',
    'FAQ_Q5': 'Welche Dokumentformate werden unterstützt?',
    'FAQ_A5': 'PDFs, Word-Dokumente und textbasierte Dateien. Bestehende Archive sind vom ersten Tag an vollständig durchsuchbar, ohne Neuformatierung oder Migration.',
    'FAQ_Q6': 'Erfordert nightwind.ai laufende Abonnements?',
    'FAQ_A6': 'Nein. Dauerlizenz. Keine wiederkehrenden Gebühren, keine Gebühren pro Arbeitsplatz, keine Verlängerungsverhandlungen. Kunden besitzen alle eingesetzten Komponenten vollständig.',
    'CONTACT_LABEL': 'Kontakt',
    'CONTACT_H2': 'Briefing anfordern.',
    'CONTACT_SUBTEXT': 'Technische Briefings und Deployment-Dokumentation sind für verifizierte Organisationen unter NDA erhältlich.',
    'FOOTER_TAGLINE': 'Airgapped KI-Dokumentenanalyse. Souveräne Technologie.',
    'FOOTER_NAV_CAP': 'Funktionen',
    'FOOTER_NAV_UC': 'Anwendungsfälle',
    'FOOTER_NAV_FAQ': 'FAQ',
    'FOOTER_NAV_CONTACT': 'Kontakt',
    'FOOTER_COPYRIGHT': '&copy; 2026 nightwind.ai. Alle Rechte vorbehalten.',
  },

  'fr': {
    'LANG_CODE': 'fr',
    'DIR': 'ltr',
    'CONF_BORDER': 'border-l-2 border-l-signal-green',
    'OG_LOCALE': 'fr_FR',
    'CANONICAL': 'https://nightwind.ai/fr/',
    'ASSET_PATH': '../',
    'ROOT_PATH': 'https://nightwind.ai/',
    'PAGE_TITLE': 'nightwind.ai | Intelligence documentaire IA en réseau isolé',
    'META_DESC': 'Intelligence documentaire IA en réseau isolé pour la défense, le renseignement et les organisations de sécurité nationale. Déploiement sur site. Aucune dépendance cloud. Totalement souverain. Licence perpétuelle.',
    'META_OG_DESC': 'Interrogez des décennies d\'archives de renseignement en langage naturel. Déployé sur site. Aucune dépendance cloud. Totalement souverain.',
    'CLASSIFICATION_BANNER': '// RENSEIGNEMENT ISOLÉ //',
    'HERO_H1': 'L\'IA documentaire<br>souveraine.',
    'HERO_SUBTEXT': 'Interrogez des décennies d\'archives de renseignement non structurées en langage naturel. Déployé sur site. Aucune dépendance cloud. Totalement souverain.',
    'HERO_TAGLINE': 'Conçu pour la défense, le renseignement et les organisations de sécurité nationale.',
    'HERO_CTA': 'DEMANDER UN BRIEFING',
    'LOCAL_NAME': '',
    'PROBLEM_LABEL': 'Le Problème',
    'PROBLEM_H2': 'Vos analystes passent plus de temps à chercher qu\'à analyser.',
    'PROBLEM_C1_LABEL': '[DONNÉES HÉRITÉES]',
    'PROBLEM_C1_TEXT': 'Des téraoctets de rapports de renseignement, d\'évaluations de terrain et de documents politiques accumulés sur des décennies — bloqués dans des formats résistant à la recherche moderne.',
    'PROBLEM_C2_LABEL': '[INEFFICACITÉ]',
    'PROBLEM_C2_TEXT': '60 à 70 % du temps des analystes est consommé par la récupération manuelle de documents. Des connaissances qui devraient émerger en quelques secondes prennent des heures ou des jours.',
    'PROBLEM_C3_LABEL': '[DÉPENDANCE FOURNISSEUR]',
    'PROBLEM_C3_TEXT': 'Les solutions existantes nécessitent une connectivité cloud et créent une dépendance à des fournisseurs étrangers — incompatibles avec les opérations souveraines et les exigences de sécurité nationale.',
    'PLATFORM_LABEL': 'La Plateforme',
    'PLATFORM_H2': 'Posez des questions. Obtenez des réponses citées. Restez isolé.',
    'CAP1_TITLE': '[01] INTERROGER EN TOUTE LANGUE',
    'CAP1_TEXT': 'Vos analystes posent des questions comme ils pensent — en français, en arabe, en anglais ou dans toute langue de travail. La plateforme parcourt l\'ensemble de votre archive documentaire et retourne en quelques secondes des réponses citées et sourcées.',
    'CAP2_TITLE': '[02] ISOLÉ PAR CONCEPTION',
    'CAP2_TEXT': 'Déployé entièrement sur site, derrière votre gap aérien. Aucune connectivité cloud. Aucune donnée ne quitte votre infrastructure. Contrôle total de la sécurité dès le premier jour.',
    'CAP3_TITLE': '[03] FLEXIBILITÉ DES MODÈLES',
    'CAP3_TEXT': 'Compatible avec les modèles d\'IA open source et propriétaires. Choisissez les modèles qui répondent à vos exigences de sécurité et de performance. Aucune dépendance à un seul fournisseur.',
    'CAP4_TITLE': '[04] LIT VOS DOCUMENTS',
    'CAP4_TEXT': 'PDF, documents Word et fichiers texte — vos archives documentaires existantes sont consultables dès le premier jour, dans toute langue, sans reformatage ni migration.',
    'POS_LABEL': 'Positionnement',
    'POS_H2': 'IA souveraine. Isolée par conception.',
    'POS_SUBTEXT': 'Conçue pour les organisations qui ne peuvent pas envoyer de données vers le cloud et qui exigent une indépendance opérationnelle totale.',
    'POS1_TITLE': 'ZÉRO CLOUD',
    'POS1_TEXT': 'Pas « optionnellement cloud ». Pas « hybride ». Isolé dès le premier jour. Vos données ne quittent jamais votre infrastructure. Jamais.',
    'POS2_TITLE': 'ZÉRO DÉPENDANCE',
    'POS2_TEXT': 'Aucun abonnement, aucun tarif par poste, aucune négociation de renouvellement. Standards ouverts. Licence perpétuelle. Vos données, vos modèles, votre souveraineté.',
    'POS3_TITLE': 'TRAÇABILITÉ TOTALE',
    'POS3_TEXT': 'Chaque requête enregistrée. Chaque réponse traçable jusqu\'aux documents sources. Responsabilité totale intégrée dans la plateforme dès la conception.',
    'UC_LABEL': 'Contexte Opérationnel',
    'UC_H2': 'Conçu pour votre environnement opérationnel.',
    'UC1_TITLE': 'ANALYSE DU RENSEIGNEMENT DÉFENSE',
    'UC1_QUOTE': 'Quelles conclusions les évaluations alliées ont-elles tirées sur les dépendances de la chaîne d\'approvisionnement de [acteur menaçant] entre 2015 et 2024 ?',
    'UC1_TEXT': 'Faites remonter des renseignements croisés issus de décennies de rapports archivés en quelques secondes. Chaîne de citations complète. Sources vérifiables par l\'analyste.',
    'UC2_TITLE': 'ACQUISITION DE DÉFENSE',
    'UC2_QUOTE': 'Quels rapports d\'évaluation font référence à des problèmes de performance de [type d\'équipement] en conditions opérationnelles ?',
    'UC2_TEXT': 'Interrogez des décennies d\'évaluations techniques, de rapports de terrain et de comptes rendus post-opérationnels sans récupération manuelle de documents.',
    'UC3_TITLE': 'POLITIQUE DE SÉCURITÉ NATIONALE',
    'UC3_QUOTE': 'Comment les évaluations de menaces pour [région] ont-elles évolué au fil des trois dernières revues stratégiques de défense ?',
    'UC3_TEXT': 'Synthétisez les évolutions temporelles à travers les documents de politique, les synthèses de renseignement et les notes ministérielles.',
    'CONF_LABEL': 'Confidentialité',
    'CONF_H2': 'Confidentialité totale. Sans exception.',
    'CONF_TEXT': 'Chaque engagement — du briefing initial au déploiement — est conduit sous NDA stricte. Les identités des clients, les configurations de déploiement et les détails opérationnels ne sont jamais divulgués, dans aucun contexte, à aucune partie, à aucune fin. Ce que vous déployez reste classifié.',
    'FAQ_LABEL': 'FAQ',
    'FAQ_H2': 'Questions fréquentes.',
    'FAQ_Q1': 'nightwind.ai nécessite-t-il une connectivité cloud ?',
    'FAQ_A1': 'Non. nightwind.ai est entièrement isolé. Tous les traitements s\'effectuent sur l\'infrastructure appartenant au client, à l\'intérieur de son propre périmètre de sécurité. Aucune donnée ne quitte jamais l\'installation.',
    'FAQ_Q2': 'Quelles langues nightwind.ai prend-il en charge ?',
    'FAQ_A2': 'Toutes les langues. Il n\'y a aucune limitation linguistique. Les opérateurs peuvent interroger en français, en arabe, en anglais, en mandarin, en russe, en espagnol ou dans toute autre langue. Les archives multilingues sont prises en charge.',
    'FAQ_Q3': 'Quel est le modèle de licence ?',
    'FAQ_A3': 'Licence perpétuelle. Aucun abonnement, aucun tarif par poste, aucune dépendance récurrente au fournisseur. Après le déploiement, les clients possèdent tous les composants.',
    'FAQ_Q4': 'nightwind.ai est-il adapté aux réseaux classifiés ?',
    'FAQ_A4': 'Oui. nightwind.ai est conçu pour les environnements classifiés et sensibles. Zéro dépendance réseau, aucune télémétrie, aucun retour d\'appel fournisseur. Compatible avec les réseaux isolés et classifiés.',
    'FAQ_Q5': 'Quels formats de documents sont pris en charge ?',
    'FAQ_A5': 'PDF, documents Word et fichiers texte. Les archives existantes dans ces formats sont entièrement consultables dès le premier jour, sans reformatage ni migration.',
    'FAQ_Q6': 'nightwind.ai exige-t-il des abonnements continus ?',
    'FAQ_A6': 'Non. Licence perpétuelle. Aucun frais récurrent, aucun tarif par poste, aucune négociation de renouvellement. Les clients possèdent intégralement tous les composants déployés.',
    'CONTACT_LABEL': 'Contact',
    'CONTACT_H2': 'Demander un briefing.',
    'CONTACT_SUBTEXT': 'Les briefings techniques et la documentation de déploiement sont disponibles pour les organisations vérifiées sous NDA.',
    'FOOTER_TAGLINE': 'Intelligence documentaire IA en réseau isolé. Technologie souveraine.',
    'FOOTER_NAV_CAP': 'Capacités',
    'FOOTER_NAV_UC': 'Cas d\'usage',
    'FOOTER_NAV_FAQ': 'FAQ',
    'FOOTER_NAV_CONTACT': 'Contact',
    'FOOTER_COPYRIGHT': '&copy; 2026 nightwind.ai. Tous droits réservés.',
  },

  'es': {
    'LANG_CODE': 'es',
    'DIR': 'ltr',
    'CONF_BORDER': 'border-l-2 border-l-signal-green',
    'OG_LOCALE': 'es_ES',
    'CANONICAL': 'https://nightwind.ai/es/',
    'ASSET_PATH': '../',
    'ROOT_PATH': 'https://nightwind.ai/',
    'PAGE_TITLE': 'nightwind.ai | Inteligencia documental IA con aislamiento de red',
    'META_DESC': 'Inteligencia documental IA aislada para defensa, inteligencia y organizaciones de seguridad nacional. Despliegue local. Sin dependencia de la nube. Totalmente soberana. Licencia perpetua.',
    'META_OG_DESC': 'Consulte décadas de archivos de inteligencia no estructurados en lenguaje natural. Desplegado localmente. Sin dependencia de la nube. Totalmente soberano.',
    'CLASSIFICATION_BANNER': '// INTELIGENCIA AISLADA //',
    'HERO_H1': 'IA documental soberana.<br>Aislada. Sin nube.',
    'HERO_SUBTEXT': 'Consulte décadas de archivos de inteligencia no estructurados en lenguaje natural. Desplegado localmente. Sin dependencia de la nube. Totalmente soberano.',
    'HERO_TAGLINE': 'Diseñado para defensa, inteligencia y organizaciones de seguridad nacional.',
    'HERO_CTA': 'SOLICITAR UN BRIEFING',
    'LOCAL_NAME': '',
    'PROBLEM_LABEL': 'El Problema',
    'PROBLEM_H2': 'Sus analistas pasan más tiempo buscando que analizando.',
    'PROBLEM_C1_LABEL': '[DATOS HEREDADOS]',
    'PROBLEM_C1_TEXT': 'Terabytes de informes de inteligencia, evaluaciones de campo y documentos de política acumulados durante décadas — bloqueados en formatos que resisten la búsqueda moderna.',
    'PROBLEM_C2_LABEL': '[INEFICIENCIA]',
    'PROBLEM_C2_TEXT': 'El 60–70% del tiempo del analista se consume en la recuperación manual de documentos. El conocimiento que debería tardar segundos tarda horas o días.',
    'PROBLEM_C3_LABEL': '[DEPENDENCIA DE PROVEEDOR]',
    'PROBLEM_C3_TEXT': 'Las soluciones existentes requieren conectividad a la nube y crean dependencia de proveedores extranjeros — incompatibles con operaciones soberanas y requisitos de seguridad nacional.',
    'PLATFORM_LABEL': 'La Plataforma',
    'PLATFORM_H2': 'Haz preguntas. Obtén respuestas citadas. Permanece aislado.',
    'CAP1_TITLE': '[01] CONSULTAR EN CUALQUIER IDIOMA',
    'CAP1_TEXT': 'Sus analistas formulan preguntas como piensan — en español, árabe, francés o cualquier idioma de trabajo. La plataforma busca en todo su archivo documental y devuelve respuestas citadas y con fuentes en segundos.',
    'CAP2_TITLE': '[02] AISLADO POR DISEÑO',
    'CAP2_TEXT': 'Desplegado íntegramente en las instalaciones, tras su air gap. Sin conectividad a la nube. Ningún dato abandona su infraestructura. Control total de seguridad desde el primer día.',
    'CAP3_TITLE': '[03] FLEXIBLE EN MODELOS',
    'CAP3_TEXT': 'Compatible con modelos de IA de código abierto y propietarios. Elija los modelos que cumplan sus requisitos de seguridad y rendimiento. Sin dependencia de un único proveedor.',
    'CAP4_TITLE': '[04] LEE SUS DOCUMENTOS',
    'CAP4_TEXT': 'PDFs, documentos Word y archivos de texto — sus archivos documentales existentes son consultables desde el primer día, en cualquier idioma, sin reformatear ni migrar.',
    'POS_LABEL': 'Posicionamiento',
    'POS_H2': 'IA soberana. Aislada por diseño.',
    'POS_SUBTEXT': 'Diseñada para organizaciones que no pueden enviar datos a la nube y requieren independencia operativa total.',
    'POS1_TITLE': 'CERO NUBE',
    'POS1_TEXT': 'No es "opcionalmente en la nube". No es "híbrido". Aislado desde el primer día. Sus datos jamás abandonan su infraestructura. Jamás.',
    'POS2_TITLE': 'SIN DEPENDENCIA',
    'POS2_TEXT': 'Sin suscripciones, sin tarifas por puesto, sin negociaciones de renovación. Estándares abiertos. Licencia perpetua. Sus datos, sus modelos, su soberanía.',
    'POS3_TITLE': 'AUDITORÍA COMPLETA',
    'POS3_TEXT': 'Cada consulta registrada. Cada respuesta trazable hasta los documentos fuente. Responsabilidad total integrada en la plataforma desde sus cimientos.',
    'UC_LABEL': 'Contexto Operativo',
    'UC_H2': 'Diseñado para su entorno operativo.',
    'UC1_TITLE': 'ANÁLISIS DE INTELIGENCIA DE DEFENSA',
    'UC1_QUOTE': '¿Qué concluyeron las evaluaciones aliadas sobre las dependencias de la cadena de suministro de [actor de amenaza] entre 2015 y 2024?',
    'UC1_TEXT': 'Localice inteligencia con referencias cruzadas de décadas de informes archivados en segundos. Cadena de citas completa. Fuentes verificables por el analista.',
    'UC2_TITLE': 'ADQUISICIÓN DE DEFENSA',
    'UC2_QUOTE': '¿Qué informes de evaluación hacen referencia a problemas de rendimiento de [tipo de equipo] en condiciones de teatro?',
    'UC2_TEXT': 'Consulte décadas de evaluaciones técnicas, informes de campo y revisiones post-acción sin recuperación manual de documentos.',
    'UC3_TITLE': 'POLÍTICA DE SEGURIDAD NACIONAL',
    'UC3_QUOTE': '¿Cómo han evolucionado las evaluaciones de amenazas para [región] en las tres últimas revisiones estratégicas de defensa?',
    'UC3_TEXT': 'Sintetice patrones temporales en documentos de política, resúmenes de inteligencia e informes ministeriales.',
    'CONF_LABEL': 'Confidencialidad',
    'CONF_H2': 'Confidencialidad total. Sin excepciones.',
    'CONF_TEXT': 'Cada compromiso — desde el briefing inicial hasta el despliegue — se lleva a cabo bajo NDA estricta. Las identidades de los clientes, las configuraciones de despliegue y los detalles operativos nunca se revelan en ningún contexto, a ninguna parte, para ningún propósito. Lo que despliegue permanece clasificado.',
    'FAQ_LABEL': 'FAQ',
    'FAQ_H2': 'Preguntas frecuentes.',
    'FAQ_Q1': '¿nightwind.ai requiere conectividad a la nube?',
    'FAQ_A1': 'No. nightwind.ai está completamente aislado. Todo el procesamiento ocurre en infraestructura propiedad del cliente, dentro de su propio perímetro de seguridad. Ningún dato abandona jamás las instalaciones.',
    'FAQ_Q2': '¿Qué idiomas admite nightwind.ai?',
    'FAQ_A2': 'Cualquier idioma. No hay limitación lingüística. Los operadores pueden consultar en español, árabe, francés, mandarín, ruso, inglés o cualquier otro idioma. Los archivos multilingües son compatibles.',
    'FAQ_Q3': '¿Cuál es el modelo de licencia?',
    'FAQ_A3': 'Licencia perpetua. Sin cuotas de suscripción, sin tarifas por puesto, sin dependencia recurrente del proveedor. Tras el despliegue, los clientes poseen todos los componentes.',
    'FAQ_Q4': '¿Es nightwind.ai adecuado para redes clasificadas?',
    'FAQ_A4': 'Sí. nightwind.ai está diseñado para entornos clasificados y sensibles. Cero dependencias de red, sin telemetría, sin retrollamadas al proveedor. Compatible con entornos de red air-gapped y clasificados.',
    'FAQ_Q5': '¿Qué formatos de documento se admiten?',
    'FAQ_A5': 'PDFs, documentos Word y archivos de texto. Los archivos existentes en estos formatos son completamente consultables desde el primer día, sin reformatear ni migrar.',
    'FAQ_Q6': '¿nightwind.ai requiere suscripciones continuas?',
    'FAQ_A6': 'No. Licencia perpetua. Sin cargos recurrentes, sin tarifas por puesto, sin negociaciones de renovación. Los clientes poseen íntegramente todos los componentes desplegados.',
    'CONTACT_LABEL': 'Contacto',
    'CONTACT_H2': 'Solicitar un briefing.',
    'CONTACT_SUBTEXT': 'Los briefings técnicos y la documentación de despliegue están disponibles para organizaciones verificadas bajo NDA.',
    'FOOTER_TAGLINE': 'IA documental soberana. Aislada. En sus instalaciones.',
    'FOOTER_NAV_CAP': 'Capacidades',
    'FOOTER_NAV_UC': 'Casos de uso',
    'FOOTER_NAV_FAQ': 'FAQ',
    'FOOTER_NAV_CONTACT': 'Contacto',
    'FOOTER_COPYRIGHT': '&copy; 2026 nightwind.ai. Todos los derechos reservados.',
  },

  'pt': {
    'LANG_CODE': 'pt',
    'DIR': 'ltr',
    'CONF_BORDER': 'border-l-2 border-l-signal-green',
    'OG_LOCALE': 'pt_BR',
    'CANONICAL': 'https://nightwind.ai/pt/',
    'ASSET_PATH': '../',
    'ROOT_PATH': 'https://nightwind.ai/',
    'PAGE_TITLE': 'nightwind.ai | Inteligência documental IA com rede isolada',
    'META_DESC': 'Inteligência documental IA isolada para defesa, inteligência e organizações de segurança nacional. Implantação local. Sem dependência de nuvem. Totalmente soberana. Licença perpétua.',
    'META_OG_DESC': 'Consulte décadas de arquivos de inteligência não estruturados em linguagem natural. Implantado localmente. Sem dependência de nuvem. Totalmente soberano.',
    'CLASSIFICATION_BANNER': '// INTELIGÊNCIA ISOLADA //',
    'HERO_H1': 'IA documental soberana.<br>Isolada. No local.',
    'HERO_SUBTEXT': 'Consulte décadas de arquivos de inteligência não estruturados em linguagem natural. Implantado localmente. Sem dependência de nuvem. Totalmente soberano.',
    'HERO_TAGLINE': 'Desenvolvido para defesa, inteligência e organizações de segurança nacional.',
    'HERO_CTA': 'SOLICITAR UM BRIEFING',
    'LOCAL_NAME': '',
    'PROBLEM_LABEL': 'O Problema',
    'PROBLEM_H2': 'Seus analistas passam mais tempo pesquisando do que analisando.',
    'PROBLEM_C1_LABEL': '[DADOS LEGADOS]',
    'PROBLEM_C1_TEXT': 'Terabytes de relatórios de inteligência, avaliações de campo e documentos de política acumulados ao longo de décadas — presos em formatos que resistem à pesquisa moderna.',
    'PROBLEM_C2_LABEL': '[INEFICIÊNCIA]',
    'PROBLEM_C2_TEXT': '60–70% do tempo do analista é consumido pela recuperação manual de documentos. Conhecimento que deveria emergir em segundos leva horas ou dias.',
    'PROBLEM_C3_LABEL': '[DEPENDÊNCIA DE FORNECEDOR]',
    'PROBLEM_C3_TEXT': 'As soluções existentes exigem conectividade à nuvem e criam dependência de fornecedores estrangeiros — incompatíveis com operações soberanas e requisitos de segurança nacional.',
    'PLATFORM_LABEL': 'A Plataforma',
    'PLATFORM_H2': 'Faça perguntas. Obtenha respostas citadas. Permaneça isolado.',
    'CAP1_TITLE': '[01] CONSULTAR EM QUALQUER IDIOMA',
    'CAP1_TEXT': 'Seus analistas fazem perguntas como pensam — em português, árabe, francês ou qualquer idioma de trabalho. A plataforma pesquisa todo o seu arquivo documental e retorna respostas citadas e com fontes em segundos.',
    'CAP2_TITLE': '[02] ISOLADO POR CONCEPÇÃO',
    'CAP2_TEXT': 'Implantado inteiramente no local, atrás do seu air gap. Sem conectividade à nuvem. Nenhum dado sai da sua infraestrutura. Controle total de segurança desde o primeiro dia.',
    'CAP3_TITLE': '[03] FLEXÍVEL EM MODELOS',
    'CAP3_TEXT': 'Compatível com modelos de IA de código aberto e proprietários. Escolha os modelos que atendam aos seus requisitos de segurança e desempenho. Sem dependência de um único fornecedor.',
    'CAP4_TITLE': '[04] LÊ SEUS DOCUMENTOS',
    'CAP4_TEXT': 'PDFs, documentos Word e arquivos de texto — seus arquivos documentais existentes são pesquisáveis desde o primeiro dia, em qualquer idioma, sem reformatação ou migração.',
    'POS_LABEL': 'Posicionamento',
    'POS_H2': 'IA soberana. Isolada por concepção.',
    'POS_SUBTEXT': 'Desenvolvida para organizações que não podem enviar dados para a nuvem e requerem independência operacional total.',
    'POS1_TITLE': 'ZERO NUVEM',
    'POS1_TEXT': 'Não é "opcionalmente em nuvem". Não é "híbrido". Isolado desde o primeiro dia. Seus dados jamais saem da sua infraestrutura. Jamais.',
    'POS2_TITLE': 'SEM DEPENDÊNCIA',
    'POS2_TEXT': 'Sem assinaturas, sem tarifas por usuário, sem negociações de renovação. Padrões abertos. Licença perpétua. Seus dados, seus modelos, sua soberania.',
    'POS3_TITLE': 'RASTREABILIDADE TOTAL',
    'POS3_TEXT': 'Cada consulta registrada. Cada resposta rastreável até os documentos-fonte. Responsabilidade total integrada na plataforma desde a fundação.',
    'UC_LABEL': 'Contexto Operacional',
    'UC_H2': 'Desenvolvido para o seu ambiente operacional.',
    'UC1_TITLE': 'ANÁLISE DE INTELIGÊNCIA DE DEFESA',
    'UC1_QUOTE': 'O que as avaliações aliadas concluíram sobre as dependências da cadeia de suprimentos de [ator de ameaça] entre 2015 e 2024?',
    'UC1_TEXT': 'Localize inteligência com referências cruzadas de décadas de relatórios arquivados em segundos. Cadeia de citações completa. Fontes verificáveis pelo analista.',
    'UC2_TITLE': 'AQUISIÇÃO DE DEFESA',
    'UC2_QUOTE': 'Quais relatórios de avaliação fazem referência a problemas de desempenho com [tipo de equipamento] em condições de teatro?',
    'UC2_TEXT': 'Consulte décadas de avaliações técnicas, relatórios de campo e revisões pós-ação sem recuperação manual de documentos.',
    'UC3_TITLE': 'POLÍTICA DE SEGURANÇA NACIONAL',
    'UC3_QUOTE': 'Como as avaliações de ameaças para [região] evoluíram nas últimas três revisões estratégicas de defesa?',
    'UC3_TEXT': 'Sintetize padrões temporais em documentos de política, resumos de inteligência e briefings ministeriais.',
    'CONF_LABEL': 'Confidencialidade',
    'CONF_H2': 'Confidencialidade total. Sem exceções.',
    'CONF_TEXT': 'Cada compromisso — do briefing inicial à implantação — é conduzido sob NDA rigoroso. Identidades de clientes, configurações de implantação e detalhes operacionais nunca são divulgados em nenhum contexto, a nenhuma parte, para nenhum propósito. O que você implanta permanece classificado.',
    'FAQ_LABEL': 'FAQ',
    'FAQ_H2': 'Perguntas frequentes.',
    'FAQ_Q1': 'nightwind.ai requer conectividade à nuvem?',
    'FAQ_A1': 'Não. nightwind.ai é totalmente isolado. Todo o processamento ocorre na infraestrutura de propriedade do cliente, dentro do seu próprio perímetro de segurança. Nenhum dado jamais sai das instalações.',
    'FAQ_Q2': 'Quais idiomas o nightwind.ai suporta?',
    'FAQ_A2': 'Qualquer idioma. Não há limitação de idioma. Os operadores podem consultar em português, árabe, francês, mandarim, russo, espanhol ou qualquer outro idioma. Arquivos multilíngues são suportados.',
    'FAQ_Q3': 'Qual é o modelo de licenciamento?',
    'FAQ_A3': 'Licença perpétua. Sem taxas de assinatura, sem cobranças por usuário, sem dependência recorrente de fornecedor. Após a implantação, os clientes possuem todos os componentes.',
    'FAQ_Q4': 'nightwind.ai é adequado para redes classificadas?',
    'FAQ_A4': 'Sim. nightwind.ai é projetado para ambientes classificados e sensíveis. Zero dependências de rede, sem telemetria, sem retorno ao fornecedor. Compatível com ambientes de rede air-gapped e classificados.',
    'FAQ_Q5': 'Quais formatos de documento são suportados?',
    'FAQ_A5': 'PDFs, documentos Word e arquivos de texto. Os arquivos existentes nesses formatos são totalmente pesquisáveis desde o primeiro dia, sem reformatação ou migração.',
    'FAQ_Q6': 'nightwind.ai requer assinaturas contínuas?',
    'FAQ_A6': 'Não. Licença perpétua. Sem taxas recorrentes, sem cobranças por usuário, sem negociações de renovação. Os clientes possuem integralmente todos os componentes implantados.',
    'CONTACT_LABEL': 'Contato',
    'CONTACT_H2': 'Solicitar um briefing.',
    'CONTACT_SUBTEXT': 'Briefings técnicos e documentação de implantação estão disponíveis para organizações verificadas sob NDA.',
    'FOOTER_TAGLINE': 'IA documental soberana. Isolada. No local.',
    'FOOTER_NAV_CAP': 'Capacidades',
    'FOOTER_NAV_UC': 'Casos de uso',
    'FOOTER_NAV_FAQ': 'FAQ',
    'FOOTER_NAV_CONTACT': 'Contato',
    'FOOTER_COPYRIGHT': '&copy; 2026 nightwind.ai. Todos os direitos reservados.',
  },

  'he': {
    'LANG_CODE': 'he',
    'DIR': 'rtl',
    'CONF_BORDER': 'border-r-2 border-r-signal-green',
    'OG_LOCALE': 'he_IL',
    'CANONICAL': 'https://nightwind.ai/he/',
    'ASSET_PATH': '../',
    'ROOT_PATH': 'https://nightwind.ai/',
    'PAGE_TITLE': 'nightwind.ai | בינה מלאכותית לניתוח מסמכים במערכת מבודדת',
    'META_DESC': 'בינה מלאכותית לניתוח מסמכים במערכת מבודדת לביטחון לאומי, מודיעין וארגוני ביטחון. פריסה מקומית. ללא תלות בענן. ריבונות מלאה. רישיון לצמיתות.',
    'META_OG_DESC': 'חקור עשורים של ארכיוני מודיעין בשפה טבעית. פריסה מקומית. ללא תלות בענן. ריבונות מלאה.',
    'CLASSIFICATION_BANNER': '// מערכת מודיעין מבודדת //',
    'HERO_H1': 'בינה מלאכותית לניתוח<br>מסמכים — מבודדת לחלוטין.',
    'HERO_SUBTEXT': 'חקור עשורים של ארכיוני מודיעין לא מובנים בשפה טבעית. פריסה מקומית. ללא תלות בענן. ריבונות מלאה.',
    'HERO_TAGLINE': 'נבנה עבור ארגוני ביטחון, מודיעין וביטחון לאומי.',
    'HERO_CTA': 'בקש תדרוך',
    'LOCAL_NAME': '',
    'PROBLEM_LABEL': 'הבעיה',
    'PROBLEM_H2': 'המנתחים שלכם מבלים יותר זמן בחיפוש מאשר בניתוח.',
    'PROBLEM_C1_LABEL': '[נתונים ישנים]',
    'PROBLEM_C1_TEXT': 'טרה-בייטים של דוחות מודיעין, הערכות שדה ומסמכי מדיניות שנצברו על פני עשורים — נעולים בפורמטים שמקשים על חיפוש מודרני.',
    'PROBLEM_C2_LABEL': '[חוסר יעילות]',
    'PROBLEM_C2_TEXT': '60–70% מזמן המנתח נצרך על ידי אחזור מסמכים ידני. ידע שאמור לצוץ בשניות לוקח שעות או ימים.',
    'PROBLEM_C3_LABEL': '[תלות בספק]',
    'PROBLEM_C3_TEXT': 'פתרונות קיימים דורשים קישוריות לענן ויוצרים תלות בספקים זרים — אינם מתאימים לפעולות ריבוניות ולדרישות ביטחון לאומי.',
    'PLATFORM_LABEL': 'הפלטפורמה',
    'PLATFORM_H2': 'שאלות. תשובות מדויקות. סוד מוחלט.',
    'CAP1_TITLE': '[01] שאילתות בכל שפה',
    'CAP1_TEXT': 'המנתחים שלכם שואלים שאלות כפי שהם חושבים — בעברית, ערבית, אנגלית או כל שפת עבודה. הפלטפורמה מחפשת בכל ארכיון המסמכים שלכם ומחזירה תשובות עם ציטוטים ומקורות בשניות.',
    'CAP2_TITLE': '[02] מבודד מהתכנון',
    'CAP2_TEXT': 'פריסה מלאה מקומית, מאחורי ה-air gap שלכם. ללא קישוריות לענן. אין נתונים שיוצאים מהתשתית שלכם. שליטת אבטחה מלאה מהיום הראשון.',
    'CAP3_TITLE': '[03] גמישות במודלים',
    'CAP3_TEXT': 'עובד עם מודלי בינה מלאכותית בקוד פתוח וקנייניים. בחר את המודלים שעונים על דרישות האבטחה והביצועים שלך. ללא תלות בספק יחיד.',
    'CAP4_TITLE': '[04] קורא את המסמכים שלכם',
    'CAP4_TEXT': 'קבצי PDF, מסמכי Word וקבצי טקסט — ארכיוני המסמכים הקיימים שלכם ניתנים לחיפוש מהיום הראשון, בכל שפה, ללא פורמט מחדש או העברה.',
    'POS_LABEL': 'מיצוב',
    'POS_H2': 'בינה מלאכותית ריבונית. מבודדת מהתכנון.',
    'POS_SUBTEXT': 'מיועדת לארגונים שאינם יכולים לשלוח נתונים לענן ודורשים עצמאות תפעולית מלאה.',
    'POS1_TITLE': 'ללא ענן',
    'POS1_TEXT': 'לא "אופציונלי בענן". לא "היברידי". מבודד מהיום הראשון. הנתונים שלכם לעולם אינם יוצאים מהתשתית שלכם. לעולם לא.',
    'POS2_TITLE': 'ללא תלות בספק',
    'POS2_TEXT': 'ללא מנויים, ללא תשלומים לכל מושב, ללא משא ומתן על חידוש. תקנים פתוחים. רישיון לצמיתות. הנתונים שלכם, המודלים שלכם, הריבונות שלכם.',
    'POS3_TITLE': 'מסלול ביקורת מלא',
    'POS3_TEXT': 'כל שאילתה מתועדת. כל תשובה ניתנת למעקב עד למסמכי המקור. אחריות מלאה מובנית בפלטפורמה מהיסוד.',
    'UC_LABEL': 'הקשר תפעולי',
    'UC_H2': 'נבנה לסביבת הפעולה שלכם.',
    'UC1_TITLE': 'ניתוח מודיעין ביטחוני',
    'UC1_QUOTE': 'אילו מסקנות הסיקו הערכות בעלות ברית לגבי תלויות שרשרת האספקה של [גורם האיום] בין 2015–2024?',
    'UC1_TEXT': 'חלץ מודיעין עם הפניות צולבות מעשורים של דוחות מאורכבים בשניות. שרשרת ציטוטים מלאה. מקורות הניתנים לאימות על ידי המנתח.',
    'UC2_TITLE': 'רכש ביטחוני',
    'UC2_QUOTE': 'אילו דוחות הערכה מתייחסים לבעיות ביצועים עם [סוג ציוד] בתנאי שדה?',
    'UC2_TEXT': 'שאל שאילתות בעשורים של הערכות טכניות, דוחות שדה וסקירות לאחר פעולה ללא אחזור מסמכים ידני.',
    'UC3_TITLE': 'מדיניות ביטחון לאומי',
    'UC3_QUOTE': 'כיצד התפתחו הערכות האיומים עבור [אזור] במהלך שלוש הסקירות האסטרטגיות הביטחוניות האחרונות?',
    'UC3_TEXT': 'סנתז דפוסים זמניים על פני מסמכי מדיניות, סיכומי מודיעין ותדרוכים משרדיים.',
    'CONF_LABEL': 'סודיות',
    'CONF_H2': 'סודיות מלאה. ללא יוצאי דופן.',
    'CONF_TEXT': 'כל מעורבות — מהתדרוך הראשוני ועד לפריסה — מתנהלת תחת NDA קפדנית. זהויות לקוחות, תצורות פריסה ופרטים תפעוליים לעולם אינם נחשפים בשום הקשר, לשום גורם, לשום מטרה. מה שאתם פורסים נשאר מסווג.',
    'FAQ_LABEL': 'שאלות נפוצות',
    'FAQ_H2': 'שאלות נפוצות.',
    'FAQ_Q1': 'האם nightwind.ai דורש קישוריות לענן?',
    'FAQ_A1': 'לא. nightwind.ai מבודד לחלוטין. כל העיבוד מתרחש על תשתית בבעלות הלקוח בתוך היקף האבטחה שלו. שום נתון לא יוצא מהמתקן אף פעם.',
    'FAQ_Q2': 'אילו שפות nightwind.ai תומך?',
    'FAQ_A2': 'כל שפה. אין מגבלת שפה. מפעילים יכולים לבצע שאילתות בעברית, ערבית, אנגלית, מנדרינית, רוסית, ספרדית או כל שפה אחרת. ארכיונים רב-לשוניים נתמכים.',
    'FAQ_Q3': 'מהו מודל הרישוי?',
    'FAQ_A3': 'רישיון לצמיתות. ללא דמי מנוי, ללא חיובים לכל מושב, ללא תלות חוזרת בספק. לאחר הפריסה, הלקוחות מחזיקים את כל הרכיבים.',
    'FAQ_Q4': 'האם nightwind.ai מתאים לרשתות מסווגות?',
    'FAQ_A4': 'כן. nightwind.ai מיועד לסביבות מסווגות ורגישות. אפס תלויות רשת, ללא טלמטריה, ללא חזרה לספק. תואם לסביבות רשת air-gapped ומסווגות.',
    'FAQ_Q5': 'אילו פורמטים של מסמכים נתמכים?',
    'FAQ_A5': 'קבצי PDF, מסמכי Word וקבצי טקסט. ארכיונים קיימים בפורמטים אלה ניתנים לחיפוש מלא מהיום הראשון, ללא פורמט מחדש או העברה.',
    'FAQ_Q6': 'האם nightwind.ai דורש מנויים שוטפים?',
    'FAQ_A6': 'לא. רישיון לצמיתות. ללא תשלומים חוזרים, ללא חיובים לכל מושב, ללא משא ומתן על חידוש. הלקוחות מחזיקים לחלוטין בכל הרכיבים הפרוסים.',
    'CONTACT_LABEL': 'צור קשר',
    'CONTACT_H2': 'בקש תדרוך.',
    'CONTACT_SUBTEXT': 'תדרוכים טכניים ותיעוד פריסה זמינים לארגונים מאומתים תחת NDA.',
    'FOOTER_TAGLINE': 'בינה מלאכותית לניתוח מסמכים — מבודדת לחלוטין. טכנולוגיה ריבונית.',
    'FOOTER_NAV_CAP': 'יכולות',
    'FOOTER_NAV_UC': 'מקרי שימוש',
    'FOOTER_NAV_FAQ': 'שאלות נפוצות',
    'FOOTER_NAV_CONTACT': 'צור קשר',
    'FOOTER_COPYRIGHT': '&copy; 2026 nightwind.ai. כל הזכויות שמורות.',
  },

}

LANG_KEYS = ['EN', 'AR', 'DE', 'FR', 'ES', 'PT', 'HE']


def generate(lang_code, strings, template):
    html = template
    for key, val in strings.items():
        html = html.replace(f'%%{key}%%', val)
    for key in LANG_KEYS:
        placeholder = f'%%LANG_ACTIVE_{key}%%'
        css = ACTIVE if key.lower() == lang_code else INACTIVE
        html = html.replace(placeholder, css)
    return html


def main():
    base = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(base, 'template.html'), 'r', encoding='utf-8') as f:
        template = f.read()

    for lang_code, strings in LANGS.items():
        html = generate(lang_code, strings, template)
        if lang_code == 'en':
            out_path = os.path.join(base, 'index.html')
        else:
            lang_dir = os.path.join(base, lang_code)
            os.makedirs(lang_dir, exist_ok=True)
            out_path = os.path.join(lang_dir, 'index.html')
        with open(out_path, 'w', encoding='utf-8') as f:
            f.write(html)
        print(f'  ✓  {out_path}')

    print('\nDone. Edit template.html + build.py, then re-run to regenerate.')


if __name__ == '__main__':
    main()
